jobs:
  - job: Test
    pool:
      vmImage: "macOS 10.13"
    steps:
    - template: build-and-test/build-and-test.yml
      parameters:
        branch: master
  - job: Release
    pool:
      vmImage: "macOS 10.13"
    dependsOn: Test
    steps:
    - template: release-framework/release-framework.yml
      parameters:
        branch: master
