parameters:
 - name: xcodeAppName
   type: string
   default: Xcode_13.1
   values:
   - Xcode_13.1
   - Xcode_12.4
   
jobs:
  - job: Test
    pool:
      vmImage: "macOS-11"
    steps:
    - template: build-and-test/build-and-test.yml
      parameters:
        branch: master
        xcodeAppName: ${{ parameters.xcodeAppName }}
  - job: Release
    pool:
      vmImage: "macOS-11"
    dependsOn: Test
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    steps:
    - template: release-framework/release-framework.yml
      parameters:
        branch: master
