jobs:
  - job: Test
    pool:
      vmImage: "macOS 10.15"
    steps:
    - template: build-and-test/build-and-test.yml
      parameters:
        branch: chore/xcode11.3
  - job: Release
    pool:
      vmImage: "macOS 10.15"
    dependsOn: Test
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    steps:
    - template: release-framework/release-framework.yml
      parameters:
        branch: chore/xcode11.3
