name: Create bump PR v0.1.9

on:
    workflow_call:
        secrets:
          envPAT:
            required: true
            
jobs:
  create-bump-pr:
    runs-on: macos-latest

    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
        
      - name: checkout
        uses: actions/checkout@v2

      - name: gh auth
        run: |
          # auth with user PAT, them the user creates the PR instead of bot
          echo ${{ secrets.envPAT }} > .githubtoken
          gh auth login --with-token < .githubtoken
          rm .githubtoken

      - name: create branch
        id: createBranch
        run: |
            BRANCH=chore/bump_$(date +%Y-%m-%d-%H%M%S)
            git config --global user.email "iosx@wire.com"
            echo "ℹ️ create branch: $BRANCH"
            git branch $BRANCH
            git checkout $BRANCH
            echo "::set-output name=BRANCH::$BRANCH"
            
      - name: update Cartfiles
        run: |
            # process Cartfile
            curl --silent https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Scripts/updateCatfile.swift --output updateCarfile.swift
            chmod +x updateCarfile.swift
            swift updateCarfile.swift ${{ secrets.envPAT }} ./Cartfile
            swift updateCarfile.swift ${{ secrets.envPAT }} ./Cartfile.private
            rm updateCarfile.swift
            
            # check Cartfile is empty, it may occur if API limit is hit.
            [ -s ./Cartfile ] || exit 1
            
      - name: Carthage update
        run: |
            ### Hack: carthage update may never done if framework dependency versions does not match. 
            ### limit the maximum amount of cpu time to 60 sec to stop the update after timeout
            ulimit -t 60; carthage update --no-build
            # Create bump PR
            
      - name: git commit and push
        run: |
            git add .
            git commit -m"chore: bump components"
            git push --set-upstream origin ${{ steps.createBranch.outputs.BRANCH }}
            echo "ℹ️ open bump PR"

      - name: create pull request
        run: |
            gh pr create --title "chore: bump components SQPIT-776" --body "Bump framework(s) version trigger by updated of: ${{ github.event.client_payload.repository }}"
